### ISSUE TITLE
listingOrder in pronunciation

### ISSUE THREAD

**Issue by simonkrek** [oasis-tcs/lexidma#28]
Do we really need listingOrder as REQUIRED in pronunciation. I would say "zero or one"?

**Comment by DavidFatDavidF** [comment]
Reviewed in TC meeting on 5th June

According to @simonkrek  it would make better business sense to only enforce the listingOrder attribute if more than one objects present.
This would be an advanced business rule (e.g. enforceable by Schemtaron in XML) but may not be as easy to enforce  in other than XML serializations.
Another viable strategy could be making it OPTIONAL with a default.
Decision postponed until we hear from @michmech

**Comment by michmech** [comment]
We have `listingOrder` properties on many object types, not just `pronunciation`. They are required but also it says everywhere in the spec that they can be **implicit from the serialization**. This means that in XML and JSON, the `listingOrder` property doesn't need to be implemented because the listing order of every item is implicit from the item's position inside its parent. The `listingOrder` property is only meant to be implemented in environments that don't preserve order out of box, such as relational databases and RDF.

**Comment by DavidFatDavidF** [comment]
From the point of view of the data model order is required. However, in some implementations order can be encoded implicitly such as XML elements or JSON arrays. In some other environments that don't have implicit ordering mechanisms order has to be encoded explicitly.
Serializarion specifications as well as direct implementations need to document how the required order information is encoded.
