### ISSUE TITLE
soundFile [core element] data type

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#54]
The property soundFile is allowed to be a filename. How do ensure portability in this case? Shouldn't we restrict to to URIs?

**Comment by michmech** [comment]
OK, now that I have thought about this, I think the cleanest way we can do it is this:

- At the model level, say that the value of `soundFile` is a “pointer to a file” or something abstract like that, regardless of how it’s implemented.

- At the level of each serialization, we specify what that actually means. In RDF, definitely a URI. In XML and JSON, probably a URI too because these serializations are intended mainly for data exchange, so portability is important. In relational databases, I’d say probably just a file name which the local implementation knows where to go to get it, because the relational database implementation is not intended for data exchange.

**Comment by jmccrae** [comment]
If it is a URI in all serializations, I don't see the point in not making it a URI in the data model. What possible serialization could come along that would require something else?

You could also specify that these are relative URLs (see [RFC1808](https://datatracker.ietf.org/doc/html/rfc1808)) like in HTML so that the following would both be possible:

```xml
<pronunciation soundFile="hello.mp3"/>
<pronunciation soundFile="https://www.example.com/hello.mp3"/>
```

**Comment by michmech** [comment]
> If it is a URI in all serializations [...]

What I'm proposing is that it is *not* a URI in all serializations. It would not be a URI in relational databases (= the last sentence in the second of my two bullet points above).

**Comment by DavidFatDavidF** [comment]
Decision Dec 12 meeting:
The data type is an IRI in all cases
Explain in the spec that the IRIs can be absolute or relative (they are both legal IRIs) 

Cascade the URI -> IRI throughout the spec

Rationale for IRI: IRI is increasingly common in languages related interoperability
IRI is interoperable with URI, i.e. all URIs are IRIs
