### ISSUE TITLE
Whitespace rules are not defined in XML

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#69]
Whitespace rules in the XML are not clearly defined. For example consider this

```xml
                <exampleTranslation>
                    <text>
                            Koroner <collocateMarker lemma="provést">provedl</collocateMarker>
                            <headwordMarker>pitvu</headwordMarker>.
                    </text>
                </exampleTranslation>
```
  
How do we know that the whitespace is a single character between 'provedl' and 'pitvu', while the whitespace before 'Koronoer' and after '.' is not part of the translation?

Blocking implementation of #61

**Comment by jmccrae** [comment]
Related is is the use of `label`s in `collocateMarkers` for which there is no example, but the whitespace rules around `label`s should be considered too

```xml
<collocateMarker>
   This is a collocate marker
   <label tag="foo"/>  <!-- is the whitespace part of the collocate marker? -->
</collocateMarker>
```

**Comment by DavidFatDavidF** [comment]
Decision Dec 12 meeting:
Explain whitespace handling in XML serialization intro
Introduce whitespace attribute on the affected elements (consider defaults)
Review xml whitespace implementation in next meeting

**Comment by michmech** [comment]
- I have added a paragraph to the “design principles” section (at the start of the XML serialization section) which states that whitespace should always be *collapsed* (which includes removing leading and trailing whitespace) unless otherwise stated.
- On each XML element that can take inline markup, I have “otherwise stated” that whitespace inside it should be *preserved*.
- I have updated the examples (in the “Examples” section) to not contradict that.

Will close automatically when pull request #75 is merged.
