### ISSUE TITLE
Some JSON properties are plural and some aren't 

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#70]
Most elements in the JSON serialization use a plural form (e.g., `parts_of_speech`) but a few don't (`etymonLanguage`, `etymonType`, `etymology`, `indicator`). Should this be made consistent

This relates to #58 

We should explain the logic for non-plural names or change.

**Comment by michmech** [comment]
My thinking when designing the JSON serialisation was that the property's name is plural when its value is an array which can contain one or more instances of a model-level object. Example: `entry.partsOfSpeech` is (in JSON) an array which takes one or more strings, each representing one part of speech. In all other cases the property name is singular.

A naming convention exists in the relational database serialization where the table names are in plural (because each contains several instances of the same type), e.g. `entries`, `senses`.

How does everybody else feel about this naming convention?

If we are keeping it, then I agree it should be clarified the *Design principles* section of each serialization affected  (JSON and relational databases).

**Comment by jmccrae** [comment]
The naming convention is good, but it is not respected by the four elements I highlighted in the original post.

**Comment by michmech** [comment]
I see. Yes you’re right about `lexicographicResource.etymonLanguage`, the name should be plural (`etymonLanguages`) because it takes an array. I’ll fix this.

You are not right about `lexicographicResource.etymonTypes` and `entry.etymonologies` though, these names already are plural. Perhaps you were looking at the *types* of objects that go into these arrays, which are (and should be) singular?

You are not right about `sense.indicator` either. It does not take an array, and so its name should not be plural.

**Comment by jmccrae** [comment]
Okay.... I see that `indicator` is a misreading on my part

`etymology` needs to be changed in Example 153

`etymonLanguage` needs to be changed in 5.2.2.1

`etymonType` should be added to Examples 167-169

**Comment by michmech** [comment]
Alright, it's very well possible that the name aren't consistent with themselves in various examples etc.

**Comment by michmech** [comment]
- I have made corrections wherever I could (but it’s possible errors/typos still linger)
- I have explained the naming convention in the “design principles” section at the start of the JSON serialization section.

Will close automatically when pull request #75 is merged.
